### ISSUE TITLE
[BUG] Cannot control weather on SGJ worlds

### ISSUE THREAD

**Issue by Noobly-Walker** [Povstalec/StargateJourney#145] opened 2024-10-27 10:09 UTC
**Describe the bug**
If it is raining on Lantea, it cannot be turned off by doing `/weather set clear`, or by sleeping

**To Reproduce**
In the Overworld, do `/weather set rain`
Go through a stargate to Lantea
Use either method (`/weather set clear` or sleep at night) to clear the weather condition
Find out that you cannot

**Comment by Povstalec** [comment] 2024-11-03 21:41
Not a bug on my side, this is Mojang's fault and it's a thing they fixed in one of the newer versions.

**Closed by Povstalec** 2024-11-03 21:41 UTC
Labels: Bug
