### ISSUE TITLE
[1.20.1] Excessive RAM usage and low FPS on Abydos

### ISSUE THREAD

**Issue by craft90** [Povstalec/StargateJourney#21] opened 2023-10-07 20:02 UTC
I went to Abydos in the new version 1.20.1-0.6.8. I went exploring for a bit and didn't get much lag. But there was a lot of log errors about the naqudah spires. After finding the abydos carthoush, I experienced a lot of lag and FPS between 2 and 3. I logged off and then back in. The FPS improved a little, but still at a low 6 - 12 fps while the RAM is still at 96%-100% used. Even when standing still and just looking around. It was a night at the time.

**Comment by Marflowerose** [comment] 2023-10-08 13:06
1.20.1 -0.6.7 had same issue with me and friend, explored and mined a bit in Abydos, found a Temple and we both started lagging in similar time, my memory usage was 90%+ at 20 gigs or so and frames dropped from 120 capped to 30. 
We gated home and tried relogging but it helped very little/none, only full client restart resolved it. I also experienced same thing in Chulak but it started right away when I entered.

**Comment by Povstalec** [comment] 2023-10-08 18:07
It's most likely caused by a bug I've had in Stellar View before, which I fixed but forgot to check if it exists elsewhere in my mods. The problem is caused by the sky renderer recreating every single star every tick instead of creating it once at the start and saving it for later use.

I've made a hotfix which will hopefully solve the issue. If not, please do inform me.

**Comment by Povstalec** [comment] 2023-10-08 19:37
Alright, so far it seems like the hotfix did solve the issue, so I'm closing it. Feel free to reopen it if it turns out there's more to it though.

**Closed by Povstalec** 2023-10-08 19:37 UTC
